version = 0.1
[default.deploy.parameters]
stack_name = "tell-me-your-story"
resolve_s3 = true
s3_prefix = "tell-me-your-story"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "Repository=\"https://github.com/drdakjak/tell-me-your-story\""
